import { joinFsPath, type FsDir } from '$lib/components/file-browser/adapters/adapter';
import { asset } from '$app/paths';
import { ASSETS_DIR, COMPONENTS_DIR } from '$lib/workspace/project-layout';

export type PremadeDeckPresetId = 'french-playing-cards' | 'number-color' | 'french-tarot';

export type PremadeDeckPreset = {
	id: PremadeDeckPresetId;
	name: string;
	description: string;
	cardCount: number;
	width: number;
	height: number;
	source: string;
	license: string;
};

type CardAsset = {
	id: string;
	nickname: string;
	fileName: string;
	content?: string;
	sourcePath?: string;
	type: string;
	fields: Record<string, string>;
};

type CreatePremadeDeckInput = {
	fileSystem: FsDir;
	deckName: string;
	presetId: PremadeDeckPresetId;
};

const FRENCH_SUITS = [
	{ id: 'spades', label: 'Spades', symbol: '&#9824;', color: '#111827' },
	{ id: 'hearts', label: 'Hearts', symbol: '&#9829;', color: '#dc2626' },
	{ id: 'diamonds', label: 'Diamonds', symbol: '&#9830;', color: '#dc2626' },
	{ id: 'clubs', label: 'Clubs', symbol: '&#9827;', color: '#111827' }
] as const;

const FRENCH_RANKS = [
	{ id: 'ace', label: 'A' },
	{ id: '2', label: '2' },
	{ id: '3', label: '3' },
	{ id: '4', label: '4' },
	{ id: '5', label: '5' },
	{ id: '6', label: '6' },
	{ id: '7', label: '7' },
	{ id: '8', label: '8' },
	{ id: '9', label: '9' },
	{ id: '10', label: '10' },
	{ id: 'jack', label: 'J' },
	{ id: 'queen', label: 'Q' },
	{ id: 'king', label: 'K' }
] as const;

const COLOR_SUITS = [
	{ id: 'red', label: 'Red', color: '#dc2626' },
	{ id: 'blue', label: 'Blue', color: '#2563eb' },
	{ id: 'green', label: 'Green', color: '#16a34a' },
	{ id: 'yellow', label: 'Yellow', color: '#ca8a04' }
] as const;

export const premadeDeckPresets: PremadeDeckPreset[] = [
	{
		id: 'french-playing-cards',
		name: 'French playing cards',
		description: '52 standard cards plus 2 jokers.',
		cardCount: 54,
		width: 63,
		height: 88,
		source: 'https://github.com/Webisso/playing-cards',
		license: 'MIT'
	},
	{
		id: 'french-tarot',
		name: 'French Tarot',
		description: '78 cards: suited cards, trumps, and Fool.',
		cardCount: 78,
		width: 70,
		height: 121,
		source: 'Generated French Tarot game deck for Digitable.',
		license: 'Project license'
	},
	{
		id: 'number-color',
		name: 'Number and color deck',
		description: 'Ranks 1 through 13 in four colors.',
		cardCount: 52,
		width: 63,
		height: 88,
		source: 'Generated by Digitable.',
		license: 'Project license'
	}
];

export const unavailablePremadeDecks = [
	{
		name: 'Bavarian playing cards',
		description: 'Needs an exact FOSS Bavarian-pattern source before it ships.'
	}
] as const;

export function getPremadeDeckPreset(id: PremadeDeckPresetId) {
	const preset = premadeDeckPresets.find((preset) => preset.id === id);
	if (!preset) throw new Error(`Unknown premade deck preset: ${id}`);
	return preset;
}

export async function createPremadeDeck({
	fileSystem,
	deckName,
	presetId
}: CreatePremadeDeckInput) {
	const preset = getPremadeDeckPreset(presetId);
	const cards = createCardAssets(preset);
	const assetDir = await fileSystem.ensureDir(joinFsPath(ASSETS_DIR, 'premade-decks', preset.id));
	if (assetDir.error) return assetDir;

	const back = createBackAsset(preset);
	const files = [
		...cards.map((card) => ({ name: card.fileName, card })),
		{
			name: back.fileName,
			card: {
				content: back.svg,
				type: 'image/svg+xml'
			}
		},
		{
			name: 'LICENSE.txt',
			card: {
				content: `${preset.name}\nSource: ${preset.source}\nLicense: ${preset.license}\n`,
				type: 'text/plain'
			}
		}
	];

	for (const file of files) {
		const sourcePath = 'sourcePath' in file.card ? file.card.sourcePath : undefined;
		const content = sourcePath
			? await fetch(asset(sourcePath)).then((response) => response.blob())
			: (file.card.content ?? '');
		const written = await assetDir.data.write(
			file.name,
			new File([content], file.name, { type: file.card.type })
		);
		if (written.error) return written;
	}

	const deckDir = await fileSystem.ensureDir(joinFsPath(COMPONENTS_DIR, deckName));
	if (deckDir.error) return deckDir;

	const frontSvg = createWrapperSvg(
		preset.width,
		preset.height,
		'card_face',
		cards[0]?.fileName ?? ''
	);
	const backSvg = createWrapperSvg(preset.width, preset.height, 'background', back.fileName);
	const csv = createCsv(
		cards.map((card) => ({
			id: card.id,
			Copies: '1',
			Nickname: card.nickname,
			card_face: `premade-decks/${preset.id}/${card.fileName}`,
			back_background: `premade-decks/${preset.id}/${back.fileName}`,
			...card.fields
		}))
	);

	const deckFiles = [
		{ name: 'front.svg', content: frontSvg, type: 'image/svg+xml' },
		{ name: 'back.svg', content: backSvg, type: 'image/svg+xml' },
		{ name: 'data.csv', content: csv, type: 'text/csv' }
	];

	for (const file of deckFiles) {
		const written = await deckDir.data.write(
			file.name,
			new File([file.content], file.name, { type: file.type })
		);
		if (written.error) return written;
	}

	return { data: undefined, error: undefined } as const;
}

function createCardAssets(preset: PremadeDeckPreset): CardAsset[] {
	if (preset.id === 'french-playing-cards') return createFrenchPlayingCards();
	if (preset.id === 'french-tarot') return createFrenchTarotCards(preset);
	return createNumberColorCards(preset);
}

function createFrenchPlayingCards(): CardAsset[] {
	const cards = FRENCH_SUITS.flatMap((suit) =>
		FRENCH_RANKS.map((rank) => {
			const id = `${rank.id}_of_${suit.id}`;
			const nickname = `${rank.label} of ${suit.label}`;
			return {
				id,
				nickname,
				fileName: `${id}.png`,
				sourcePath: `/premade-decks/webisso/png/${id}.png`,
				type: 'image/png',
				fields: { rank: rank.label, suit: suit.label }
			};
		})
	);

	return [
		...cards,
		createJokerCard('red_joker', 'Red Joker'),
		createJokerCard('black_joker', 'Black Joker')
	];
}

function createJokerCard(id: string, nickname: string): CardAsset {
	return {
		id,
		nickname,
		fileName: `${id}.png`,
		sourcePath: `/premade-decks/webisso/png/${id}.png`,
		type: 'image/png',
		fields: { rank: 'Joker', suit: 'Joker' }
	};
}

function createNumberColorCards(preset: PremadeDeckPreset): CardAsset[] {
	return COLOR_SUITS.flatMap((color) =>
		Array.from({ length: 13 }, (_, index) => {
			const rank = String(index + 1);
			const id = `${color.id}_${rank}`;
			const nickname = `${color.label} ${rank}`;
			return {
				id,
				nickname,
				fileName: `${id}.svg`,
				content: createCardFaceSvg({
					width: preset.width,
					height: preset.height,
					title: rank,
					subtitle: color.label,
					center: rank,
					color: color.color,
					accent: color.color
				}),
				type: 'image/svg+xml',
				fields: { rank, color: color.label }
			};
		})
	);
}

function createFrenchTarotCards(preset: PremadeDeckPreset): CardAsset[] {
	const suited = FRENCH_SUITS.flatMap((suit) =>
		[
			...Array.from({ length: 10 }, (_, index) => ({
				id: String(index + 1),
				label: String(index + 1)
			})),
			{ id: 'jack', label: 'J' },
			{ id: 'knight', label: 'C' },
			{ id: 'queen', label: 'Q' },
			{ id: 'king', label: 'K' }
		].map((rank) => {
			const id = `tarot_${rank.id}_of_${suit.id}`;
			const nickname = `${rank.label} of ${suit.label}`;
			return {
				id,
				nickname,
				fileName: `${id}.svg`,
				content: createCardFaceSvg({
					width: preset.width,
					height: preset.height,
					title: rank.label,
					subtitle: suit.label,
					center: suit.symbol,
					color: suit.color,
					accent: suit.color
				}),
				type: 'image/svg+xml',
				fields: { rank: rank.label, suit: suit.label, tarot_group: 'Suit' }
			};
		})
	);

	const trumps = Array.from({ length: 21 }, (_, index) => {
		const rank = String(index + 1);
		const id = `tarot_trump_${rank.padStart(2, '0')}`;
		return {
			id,
			nickname: `Trump ${rank}`,
			fileName: `${id}.svg`,
			content: createCardFaceSvg({
				width: preset.width,
				height: preset.height,
				title: rank,
				subtitle: 'Trump',
				center: rank,
				color: '#7c3aed',
				accent: '#7c3aed'
			}),
			type: 'image/svg+xml',
			fields: { rank, suit: 'Trump', tarot_group: 'Trump' }
		};
	});

	const fool = {
		id: 'tarot_fool',
		nickname: 'Fool',
		fileName: 'tarot_fool.svg',
		content: createCardFaceSvg({
			width: preset.width,
			height: preset.height,
			title: 'Fool',
			subtitle: 'Oudler',
			center: '0',
			color: '#0f766e',
			accent: '#0f766e'
		}),
		type: 'image/svg+xml',
		fields: { rank: 'Fool', suit: 'Fool', tarot_group: 'Oudler' }
	};

	return [...suited, ...trumps, fool];
}

function createBackAsset(preset: PremadeDeckPreset) {
	return {
		fileName: 'card_back.svg',
		svg: `<svg xmlns="http://www.w3.org/2000/svg" width="${preset.width}mm" height="${preset.height}mm" viewBox="0 0 ${preset.width} ${preset.height}">
<rect width="${preset.width}" height="${preset.height}" rx="4" fill="#172554"/>
<rect x="5" y="5" width="${preset.width - 10}" height="${preset.height - 10}" rx="3" fill="#1d4ed8" stroke="#dbeafe" stroke-width="1.5"/>
<path d="M ${preset.width / 2} 13 L ${preset.width - 12} ${preset.height / 2} L ${preset.width / 2} ${preset.height - 13} L 12 ${preset.height / 2} Z" fill="none" stroke="#dbeafe" stroke-width="1.2"/>
<text x="${preset.width / 2}" y="${preset.height / 2 + 3}" text-anchor="middle" font-family="serif" font-size="7" fill="#dbeafe">Digitable</text>
</svg>`
	};
}

function createWrapperSvg(width: number, height: number, imageId: string, fileName: string) {
	return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}">
<image id="${imageId}" href="${fileName}" x="0" y="0" width="${width}" height="${height}" preserveAspectRatio="none"/>
</svg>`;
}

function createCardFaceSvg({
	width,
	height,
	title,
	subtitle,
	center,
	color,
	accent
}: {
	width: number;
	height: number;
	title: string;
	subtitle: string;
	center: string;
	color: string;
	accent: string;
}) {
	return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}">
<rect width="${width}" height="${height}" rx="4" fill="#fffaf0"/>
<rect x="3" y="3" width="${width - 6}" height="${height - 6}" rx="3" fill="#ffffff" stroke="${accent}" stroke-width="1.4"/>
<text x="7" y="12" font-family="serif" font-size="8" font-weight="700" fill="${color}">${escapeXml(title)}</text>
<text x="7" y="20" font-family="serif" font-size="8" fill="${color}">${center}</text>
<text x="${width / 2}" y="${height / 2 + 8}" text-anchor="middle" font-family="serif" font-size="${Math.min(width, height) / 2.7}" font-weight="700" fill="${color}">${center}</text>
<text x="${width / 2}" y="${height - 12}" text-anchor="middle" font-family="sans-serif" font-size="6" fill="#374151">${escapeXml(subtitle)}</text>
<g transform="rotate(180 ${width / 2} ${height / 2})">
<text x="7" y="12" font-family="serif" font-size="8" font-weight="700" fill="${color}">${escapeXml(title)}</text>
<text x="7" y="20" font-family="serif" font-size="8" fill="${color}">${center}</text>
</g>
</svg>`;
}

function createCsv(rows: Record<string, string>[]) {
	const headers = Array.from(new Set(rows.flatMap((row) => Object.keys(row))));
	return [
		headers.join(','),
		...rows.map((row) => headers.map((header) => escapeCsv(row[header] ?? '')).join(','))
	].join('\n');
}

function escapeCsv(value: string) {
	if (!/[",\n\r]/.test(value)) return value;
	return `"${value.replace(/"/g, '""')}"`;
}

function escapeXml(value: string) {
	return value
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}
