replicate-api-token: ENC[AES256_GCM,data:BOCZ,iv:mdrMT3ZAdyZSJVaCEm5c5xAXg7MfucAZWIW0chctKbc=,tag:M+kyAuFejxPgEODtx4RwuQ==,type:str]
s3-access-key-id: ENC[AES256_GCM,data:2ozAltOgb0tk/ZdSBFU6Q81tAnm9xmt4Tw==,iv:9UJrudPl2R1IP852bkjwkEEkckhw4A1KuaYDHRuRfFA=,tag:BZUqyLijUCox4YGqX1vJfg==,type:str]
s3-secret-access-key: ENC[AES256_GCM,data:oehYbInNsSf1AGlcO0GsObnqxsWQFtn0rxASwwBuyg==,iv:QJWC83/pMNaBTemtYqc3VT3LT5WXNKXISFhZDqcP2pU=,tag:nJe9kmFbS++Rqz9/kPy7eQ==,type:str]
google-client-id: ENC[AES256_GCM,data:ZQtbPX0RwwnhAhMTMtDIpzASaX9SreMap08NBmf2BwxHBjJqMml6y0+DoGiGq1g3QBZ3Ln9caoQFy8NbRaWzFmld0gYugxyC,iv:99IbHWl8nXkpTZF3TXkWgTqRIoyik2b/ZrW1b4wePOw=,tag:N+jkZbgH+IgqdvvOiDafdQ==,type:str]
google-client-secret: ENC[AES256_GCM,data:uSffdhIxHRvW444U+okyvpUMyvDvpnX6bxOv4yIxgy0Xyfg=,iv:nlLKzffi0rrplMNxmOZ44bskhtsN01Evfe8F8R0kAGQ=,tag:O9EcOc69Cv51nbu7wAqtpA==,type:str]
kit-api-key: ENC[AES256_GCM,data:GUm0Tbl0AWwcDxIAlv2l11SgcapFa2XDt7RR60fXInTxZ53G,iv:Rdx+QZ7ckzOGDSRMSQegVqNLpY5W5YIt6SKKxfvbgJM=,tag:bROgrxlDd6asLjiUkR71jw==,type:str]
sops:
  age:
    - recipient: age1s2x82wv62ydyxsk7v68559r74vfx87znqvsnpp8drqfz29adp98qmcdas8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWklnR3h0TjF3NnlNZXNQ
        UkJpeFo3RXhSNEcxOWhlUHhqRHNYV0RIeVQ0CjhpZkMzYVV3SW9ONDErNTlhQ3JZ
        dnlZUlZHbDFZa000K09zQ3NSeFlsU2cKLS0tIEtFQUpSSkRxVVNVVzRUdWJGaFRq
        aURKK2ZSWnJRelRqenAwb1ZUYzU0WEEKBBSHAB4/hsKDkQGgsPSiZJu006VJ9fMV
        geAUpZ9bbSkNEClqArfKhmLtDwEmYR1OF6eIKbCIWPztU/xHGgwfjg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age12xpefpttk7uwzg8crlsr78frkjxhw2k8cayxfl7qfc6jjv07espqfarw0z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOUN2allEWEtPYWlhUVR6
        SG81MW1vOUFOL1pzUXE2VDhta0hobzdRdVJNCmpYd3RiWXg0OUZoMzlINGtsQ21k
        TVZnZTg1WVFYd0V6c0liUlZYbDV2Mm8KLS0tIDYwMmlLZm9tUzNGelFVMDhZMzZJ
        VURrbHJXMSt6a3hvQTlGaEpvcEZFMzgKsy+E87FKIFyJasnwTzGUnMQNx8iNzVKO
        19zT1/Q+VNkLScwRB/uTD7MYdauj+0MYPqANy/qKE30QFYH3npGzfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-05-25T17:57:17Z'
  mac: ENC[AES256_GCM,data:hcQraId/9NlfwTP5smq52V67MluewZR7dEqcBpGl4BhSG0tBsovDH/m5JFE7Xmq+DIgTU4IR8pikImEMb5jcwipjr17O/m/nbePctcug4wGbZMxKelssKSbNW3+/corGsCMhax/cepCsa5JtMo9NCb9yVN2AoIPHrcT6GJmWe40=,iv:f2U4Y9y8Vmq/MjXAfwPcq2gC3XADRZwPKqofMDI/ynM=,tag:AhIqTFce8j+jQ54GOGU6qQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
