replicate-api-token: ENC[AES256_GCM,data:BOCZ,iv:mdrMT3ZAdyZSJVaCEm5c5xAXg7MfucAZWIW0chctKbc=,tag:M+kyAuFejxPgEODtx4RwuQ==,type:str]
sops:
  age:
    - recipient: age1s2x82wv62ydyxsk7v68559r74vfx87znqvsnpp8drqfz29adp98qmcdas8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWklnR3h0TjF3NnlNZXNQ
        UkJpeFo3RXhSNEcxOWhlUHhqRHNYV0RIeVQ0CjhpZkMzYVV3SW9ONDErNTlhQ3JZ
        dnlZUlZHbDFZa000K09zQ3NSeFlsU2cKLS0tIEtFQUpSSkRxVVNVVzRUdWJGaFRq
        aURKK2ZSWnJRelRqenAwb1ZUYzU0WEEKBBSHAB4/hsKDkQGgsPSiZJu006VJ9fMV
        geAUpZ9bbSkNEClqArfKhmLtDwEmYR1OF6eIKbCIWPztU/xHGgwfjg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age12xpefpttk7uwzg8crlsr78frkjxhw2k8cayxfl7qfc6jjv07espqfarw0z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOUN2allEWEtPYWlhUVR6
        SG81MW1vOUFOL1pzUXE2VDhta0hobzdRdVJNCmpYd3RiWXg0OUZoMzlINGtsQ21k
        TVZnZTg1WVFYd0V6c0liUlZYbDV2Mm8KLS0tIDYwMmlLZm9tUzNGelFVMDhZMzZJ
        VURrbHJXMSt6a3hvQTlGaEpvcEZFMzgKsy+E87FKIFyJasnwTzGUnMQNx8iNzVKO
        19zT1/Q+VNkLScwRB/uTD7MYdauj+0MYPqANy/qKE30QFYH3npGzfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-04-26T10:33:07Z'
  mac: ENC[AES256_GCM,data:t/pYIFiR7CHcpSCdLkfiRn9GUvDkCch3AYpn8+iIGBcQ22uJrxwxSVx8PdPdaKnnL0P2Etjsfh0tlc4/HwHl1Yc5cv/KQ6RN4MSI3LIapDki/ENa+8hYVd/EzN6XzGRJyC77a7p88CSNamVieD/mLvBkGiIKYSGGABjx+1UaA6s=,iv:h3Q4zOlpADPnWPzimuM9sjHX600GKzDvn1B9Dx0JL9Q=,tag:u3IDLZwBJGTdziwXyFF9AQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
