replicate-api-token: ENC[AES256_GCM,data:BOCZ,iv:mdrMT3ZAdyZSJVaCEm5c5xAXg7MfucAZWIW0chctKbc=,tag:M+kyAuFejxPgEODtx4RwuQ==,type:str]
s3-access-key-id: ENC[AES256_GCM,data:2ozAltOgb0tk/ZdSBFU6Q81tAnm9xmt4Tw==,iv:9UJrudPl2R1IP852bkjwkEEkckhw4A1KuaYDHRuRfFA=,tag:BZUqyLijUCox4YGqX1vJfg==,type:str]
s3-secret-access-key: ENC[AES256_GCM,data:oehYbInNsSf1AGlcO0GsObnqxsWQFtn0rxASwwBuyg==,iv:QJWC83/pMNaBTemtYqc3VT3LT5WXNKXISFhZDqcP2pU=,tag:nJe9kmFbS++Rqz9/kPy7eQ==,type:str]
google-client-id: ENC[AES256_GCM,data:ZQtbPX0RwwnhAhMTMtDIpzASaX9SreMap08NBmf2BwxHBjJqMml6y0+DoGiGq1g3QBZ3Ln9caoQFy8NbRaWzFmld0gYugxyC,iv:99IbHWl8nXkpTZF3TXkWgTqRIoyik2b/ZrW1b4wePOw=,tag:N+jkZbgH+IgqdvvOiDafdQ==,type:str]
google-client-secret: ENC[AES256_GCM,data:uSffdhIxHRvW444U+okyvpUMyvDvpnX6bxOv4yIxgy0Xyfg=,iv:nlLKzffi0rrplMNxmOZ44bskhtsN01Evfe8F8R0kAGQ=,tag:O9EcOc69Cv51nbu7wAqtpA==,type:str]
kit-api-key: ENC[AES256_GCM,data:GUm0Tbl0AWwcDxIAlv2l11SgcapFa2XDt7RR60fXInTxZ53G,iv:Rdx+QZ7ckzOGDSRMSQegVqNLpY5W5YIt6SKKxfvbgJM=,tag:bROgrxlDd6asLjiUkR71jw==,type:str]
discord-client-id: ENC[AES256_GCM,data:Sppe6I/jXEUL2BBR+O+h/4yTEw==,iv:kQaisJjMZc9HmoNDgGp1vJAwNQG2RGCr+R66CBHNse0=,tag:pi9pOmpt+kyPFilfO6KXsA==,type:int]
discord-client-secret: ENC[AES256_GCM,data:w2GsgYI+QkCxypgvjOYU/O8axMfmqhoXOVpWXWHAiOI=,iv:xw/mInTZ7ntIIB9qwOoLbNusUkOBdIqBt+QV6dT6DL4=,tag:KrvjJJWsCyWdHZpgVvzb6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWklnR3h0TjF3NnlNZXNQ
        UkJpeFo3RXhSNEcxOWhlUHhqRHNYV0RIeVQ0CjhpZkMzYVV3SW9ONDErNTlhQ3JZ
        dnlZUlZHbDFZa000K09zQ3NSeFlsU2cKLS0tIEtFQUpSSkRxVVNVVzRUdWJGaFRq
        aURKK2ZSWnJRelRqenAwb1ZUYzU0WEEKBBSHAB4/hsKDkQGgsPSiZJu006VJ9fMV
        geAUpZ9bbSkNEClqArfKhmLtDwEmYR1OF6eIKbCIWPztU/xHGgwfjg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s2x82wv62ydyxsk7v68559r74vfx87znqvsnpp8drqfz29adp98qmcdas8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOUN2allEWEtPYWlhUVR6
        SG81MW1vOUFOL1pzUXE2VDhta0hobzdRdVJNCmpYd3RiWXg0OUZoMzlINGtsQ21k
        TVZnZTg1WVFYd0V6c0liUlZYbDV2Mm8KLS0tIDYwMmlLZm9tUzNGelFVMDhZMzZJ
        VURrbHJXMSt6a3hvQTlGaEpvcEZFMzgKsy+E87FKIFyJasnwTzGUnMQNx8iNzVKO
        19zT1/Q+VNkLScwRB/uTD7MYdauj+0MYPqANy/qKE30QFYH3npGzfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12xpefpttk7uwzg8crlsr78frkjxhw2k8cayxfl7qfc6jjv07espqfarw0z
  lastmodified: '2026-07-05T18:34:13Z'
  mac: ENC[AES256_GCM,data:pYJoCA6ZFB6j/Qbsk7GrcuABp28+uh40TxinY8m56BligbXhSSWrMX50gTNjrmBK0iDiOxAnmNL7bWDdIm0DN5SqQKpLUl00oWRC27BrypnMQlzV9XvUl1srXWrZNNTloDr0+Q1I/8Z93THZ9xjXvdishcYz/MQFjdYH0JpMcPI=,iv:P8mLp4WwWV56x2+YeAQgCShu0SKryzH/wB9BwZ3OM3A=,tag:VETEeKmv327DPWQGnG9XZQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
