export const suggestedTags = [
	'Fantasy',
	'Sci-Fi',
	'Historical',
	'Mystery',
	'Strategy',
	'Adventure',
	'Horror',
	'Educational',
	'Family',
	'Medieval',
	'Ancient Civilizations',
	'Post-Apocalyptic',
	'Cyberpunk',
	'Steampunk',
	'Underwater',
	'Outer Space',
	'Dystopian Future',
	'Wild West',
	'Feudal Japan',
	'Renaissance',
	'Prehistoric',
	'Victorian Era',
	'World War I',
	'World War II',
	'Cold War',
	'Modern Day',
	'Mythological',
	'Lost City',
	'Jungle',
	'Desert',
	'Arctic',
	'Island',
	'Pirate Seas',
	'Haunted House',
	'Urban Cityscape',
	'Space Colony',
	'Interdimensional',
	'Time Travel',
	'Alternate History',
	'High Seas Exploration',
	'Mountain Expedition',
	'Space Station',
	'Fantasy Kingdom',
	'Ancient Egypt',
	'Ancient Rome',
	'Ancient Greece',
	'Martian Frontier',
	'Deep Space Exploration'
];

